import {test} from 'node:test';import assert from 'node:assert/strict';
import {createOllama,SYSTEM_PROMPT,generationSchema,DEFAULT_TIMEOUT_MS,timeoutFromEnv} from '../src/ollama.mjs';import {PRIMARY_MODEL} from '../src/report.mjs';
const input={description:'The save operation fails in our account screen.',environment:'test',logs:'HTTP 409',mode:'ai',image:{id:'screenshot-1',dataUrl:'data:image/png;base64,eA=='}};
const report=()=>({summary:'The supplied evidence suggests a save failure.',observations:[{text:'The supplied log records an error.',source:'logs',quote:'HTTP 409',imageRef:''}],visualObservations:[{text:'A notification appears visible.',source:'visual',quote:'',imageRef:'screenshot-1'}],steps:['Inspect the save response.'],questions:['Which version is affected?'],hypotheses:[],tests:[]});
function mock({installed=true,vision=true,content=report(),contents=null,timeout=false,status=200}={}){const requests=[];let chat=0;return {requests,fetchImpl:async(url,opts)=>{const path=new URL(url).pathname;requests.push({path,opts});if(path==='/api/version')return Response.json({version:'0.33.1'});if(path==='/api/tags')return Response.json({models:installed?[{name:PRIMARY_MODEL,digest:'sha256:test'}]:[]});if(path==='/api/show')return Response.json({capabilities:vision?['vision']:['completion'],license:'Apache License Version 2.0'});if(timeout)return new Promise((resolve,reject)=>{const t=setTimeout(resolve,1000);opts.signal.addEventListener('abort',()=>{clearTimeout(t);reject(opts.signal.reason);},{once:true});});const selected=contents?contents[Math.min(chat++,contents.length-1)]:content;return Response.json({message:{content:typeof selected==='string'?selected:JSON.stringify(selected)},done:true},{status});}};}
test('Ollama receives one bounded schema-constrained multimodal request at temperature zero',async()=>{const m=mock();const client=createOllama(m);const r=await client.analyze(input);assert.equal(client.timeoutMs,300000);assert.equal(r.metadata.visualEvidenceUsed,true);assert.equal(r.metadata.model,PRIMARY_MODEL);const chats=m.requests.filter(r=>r.path==='/api/chat');assert.equal(chats.length,1);const body=JSON.parse(chats[0].opts.body);assert.equal(body.options.temperature,0);assert.equal(body.options.num_predict,1200);assert.equal(body.options.num_gpu,0);assert.equal(body.stream,false);assert.equal(body.messages[1].images[0],'eA==');assert.match(body.messages[0].content,/UNTRUSTED/);assert.match(SYSTEM_PROMPT,/never instructions/i);assert.equal(body.format.additionalProperties,false);});
test('retrieved documentation is passed as untrusted guidance and preserved separately',async()=>{const m=mock();const client=createOllama(m);const knowledge={product:'oic',durationMs:4,references:[{id:'oic-1',product:'Oracle Integration',title:'Troubleshoot',heading:'Activity stream',url:'https://docs.oracle.com/example',excerpt:'Review the activity stream for the failed integration instance.'}]};const result=await client.analyze({...input,product:'oic'},{knowledge});const chat=JSON.parse(m.requests.find(r=>r.path==='/api/chat').opts.body);const payload=JSON.parse(chat.messages[1].content);assert.equal(payload.technicalReferences[0].id,'oic-1');assert.match(chat.messages[0].content,/not case evidence/i);assert.equal(result.technicalReferences[0].id,'oic-1');assert.equal(result.metadata.knowledgeReferenceCount,1);});
test('one small constrained repair can correct only an unsafe causal summary',async()=>{const unsafe={...report(),summary:'The save fails because of a version conflict.'};const safeSummary='The supplied evidence shows a failed save response alongside the reported behavior.';const m=mock({contents:[unsafe,{summary:safeSummary}]});const result=await createOllama(m).analyze(input);assert.equal(result.summary,safeSummary);assert.equal(result.metadata.safetyRepairAttempted,true);assert.equal(result.metadata.safetyRepairSucceeded,true);assert.ok(result.metadata.stageTimingMs.initialGenerationMs>=0);assert.ok(result.metadata.stageTimingMs.summaryRepairMs>=0);const chats=m.requests.filter(r=>r.path==='/api/chat');assert.equal(chats.length,2);const repair=JSON.parse(chats[1].opts.body);assert.deepEqual(Object.keys(repair.format.properties),['summary']);assert.equal(repair.options.num_predict,100);assert.equal(repair.messages.length,2);assert.match(repair.messages[1].content,/unsafeSummary/);});
test('an unsafe summary repair is still rejected and never becomes a report',async()=>{const unsafe={...report(),summary:'The save fails because of a version conflict.'};const m=mock({contents:[unsafe,{summary:unsafe.summary}]});await assert.rejects(createOllama(m).analyze(input),/rejected after one safety repair/);assert.equal(m.requests.filter(r=>r.path==='/api/chat').length,2);});
test('default timeout is five minutes and environment overrides are bounded',()=>{assert.equal(DEFAULT_TIMEOUT_MS,300000);assert.equal(timeoutFromEnv(undefined),300000);assert.equal(timeoutFromEnv('420000'),420000);for(const value of ['abc','29999','600001','42.5'])assert.throws(()=>timeoutFromEnv(value),/OLLAMA_TIMEOUT_MS/);});
test('missing model, unavailable Ollama and unsupported vision are actionable',async()=>{for(const opts of [{installed:false},{vision:false}]){const client=createOllama(mock(opts));assert.equal((await client.readiness()).ready,false);await assert.rejects(client.analyze(input),e=>e.status===503);}assert.equal((await createOllama({fetchImpl:async()=>{throw Error('offline');}}).readiness()).ready,false);});
test('timeouts expose safe phase timing and cancellation does not fall back to demo',async()=>{await assert.rejects(createOllama({...mock({timeout:true}),timeoutMs:15}).analyze(input),e=>e.status===504&&e.diagnostics.phase==='initial-generation'&&e.diagnostics.generationAttempts===1&&e.diagnostics.initialGenerationMs>=0);const controller=new AbortController();setTimeout(()=>controller.abort(),20);await assert.rejects(createOllama(mock({timeout:true})).analyze(input,{signal:controller.signal}),e=>e.status===499&&e.diagnostics.phase==='initial-generation');});
test('invalid JSON, schema, citationless responses and HTTP failures are rejected',async()=>{for(const content of ['not json',{summary:'only summary'},{...report(),observations:[{text:'Invented',source:'logs',quote:'HTTP 200',imageRef:''}],visualObservations:[]}])await assert.rejects(createOllama(mock({content})).analyze(input),e=>e.status===502);await assert.rejects(createOllama(mock({status:500})).analyze(input),/HTTP 500/);});
test('cloud Ollama URLs are prohibited',()=>assert.throws(()=>createOllama({baseURL:'https://example.com'}),/loopback/));
test('cloud or arbitrary model tags cannot receive evidence',async()=>{let fetched=false;const client=createOllama({model:'cloud-model:latest',fetchImpl:async()=>{fetched=true;throw Error('must not fetch');}});assert.equal((await client.readiness()).ready,false);await assert.rejects(client.analyze(input),/approved local model/);assert.equal(fetched,false);});
test('generation separates text and visual source constraints',()=>{const s=generationSchema(input);assert.deepEqual(s.properties.observations.items.properties.imageRef.enum,['']);assert.deepEqual(s.properties.visualObservations.items.properties.imageRef.enum,['screenshot-1']);assert.deepEqual(s.properties.visualObservations.items.properties.quote.enum,['']);assert.equal(s.properties.visualObservations.minItems,1);const text=generationSchema({...input,image:null,logs:''});assert.equal(text.properties.visualObservations.maxItems,0);assert.deepEqual(text.properties.observations.items.properties.source.enum,['description']);});
