import {createRequire} from 'node:module';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {fileURLToPath} from 'node:url';import {once} from 'node:events';import assert from 'node:assert/strict';
import {createServer} from '../server.mjs';import {demoReport,validateReport,finishReport,reportMarkdown,PRIMARY_MODEL} from '../src/report.mjs';
const {chromium}=createRequire(import.meta.url)('playwright');
const outputDir=new URL('../output/playwright/',import.meta.url);await mkdir(outputDir,{recursive:true});
let ready=true,fail=false,delay=0;
const ollama={timeoutMs:300000,readiness:async()=>({ready,model:PRIMARY_MODEL,vision:ready,version:'0.33.1',error:ready?undefined:'Model not installed. Run setup.'}),analyze:async(input,{signal,knowledge})=>{if(delay)await new Promise((resolve,reject)=>{const timer=setTimeout(resolve,delay);signal.addEventListener('abort',()=>{clearTimeout(timer);reject(Object.assign(Error('Cancelled'),{status:499}));},{once:true});});if(fail)throw Object.assign(Error('AI response rejected: invalid schema'),{status:502});const d=demoReport(input);const raw=Object.fromEntries(['summary','steps','questions','hypotheses','tests'].map(k=>[k,d[k]]));raw.observations=d.observations.map(({text,source,quote,imageRef})=>({text,source,quote,imageRef}));if(input.image)raw.observations.push({text:'The screenshot appears to show success alongside HTTP 409.',source:'visual',quote:'',imageRef:'screenshot-1'});return finishReport(validateReport(raw,input),{input,mode:'ai',model:PRIMARY_MODEL,digest:'mock-browser-test',durationMs:42,knowledge});}};
const server=createServer({ollama});server.listen(0,'127.0.0.1');await once(server,'listening');const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||undefined});const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
const external=[];await context.route('**/*',route=>{const url=new URL(route.request().url());if(url.hostname!=='127.0.0.1'){external.push(url.href);return route.abort();}return route.continue();});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const checks=[];
async function check(name,fn){await fn();checks.push(name);console.log('PASS '+name);}
async function sample(){await page.locator('#sample').click();await page.locator('#preview-wrap:not([hidden])').waitFor();await page.waitForFunction(()=>document.querySelector('#preview').naturalWidth>0);}
async function generate(){await page.locator('#analyze').click();await page.locator('#export:not([disabled])').waitFor();}
try{
  await check('submission waits for sample screenshot decoding',async()=>{
    let release;const gate=new Promise(resolve=>{release=resolve;});
    await page.route('**/sample.png',async route=>{await gate;await route.continue();});
    try{await page.goto(base+'/?demo');await page.locator('#sample').click();assert.equal(await page.locator('#analyze').isDisabled(),true);release();await page.locator('#preview-wrap:not([hidden])').waitFor();await page.waitForFunction(()=>!document.querySelector('#analyze').disabled);}
    finally{release();await page.unroute('**/sample.png');}
  });
  await check('drag and drop accepts exactly one image',async()=>{
    const b64=(await readFile(new URL('../public/sample.png',import.meta.url))).toString('base64');
    async function drop(count){await page.evaluate(({b64,count})=>{const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));const dataTransfer=new DataTransfer();for(let i=0;i<count;i++)dataTransfer.items.add(new File([bytes],'drop-'+i+'.png',{type:'image/png'}));document.querySelector('#drop-zone').dispatchEvent(new DragEvent('drop',{dataTransfer,bubbles:true}));},{b64,count});}
    await drop(2);assert.match(await page.locator('#error').innerText(),/exactly one/);await drop(1);await page.waitForFunction(()=>!document.querySelector('#analyze').disabled);assert.equal(await page.locator('#preview-wrap').isVisible(),true);assert.equal(await page.locator('#error').innerText(),'');
  });
  await check('hosted-mode demonstration has no API calls or visual analysis',async()=>{const api=[];page.on('request',r=>{if(r.url().includes('/api/'))api.push(r.url());});await page.goto(base+'/?demo');await sample();await generate();assert.match(await page.locator('#report').innerText(),/Deterministic demonstration/);assert.equal(await page.locator('.evidence-image').count(),0);assert.deepEqual(api,[]);await page.screenshot({path:fileURLToPath(new URL('hosted-demo.png',outputDir)),fullPage:true});});
  await check('page shows compact run details while downloads retain full provenance',async()=>{const downloads={};for(const [id,ext] of [['export','md'],['export-json','json']]){const pending=page.waitForEvent('download');await page.locator('#'+id).click();const d=await pending;assert.equal(d.suggestedFilename(),'repromate-investigation.'+ext);downloads[ext]=await readFile(await d.path(),'utf8');}const report=JSON.parse(downloads.json);assert.equal(downloads.md,reportMarkdown(report));const visible=await page.locator('#report').innerText();assert.ok(visible.includes(report.summary));assert.match(visible,/Deterministic demo · Browser-only · Screenshot not analyzed/);assert.doesNotMatch(visible,/Metadata & evidence provenance/);assert.doesNotMatch(visible,/modelDigest/);assert.equal(report.metadata.mode,'demo');assert.ok(report.metadata.processingDurationMs>=0);assert.ok(downloads.md.includes('## Metadata'));});
  await check('screenshot removal clears preview and previous report',async()=>{await page.locator('#remove').click();assert.equal(await page.locator('#preview-wrap').isVisible(),false);assert.equal(await page.locator('#export').isDisabled(),true);});
  await check('local readiness shows references before AI and then renders the complete report',async()=>{await page.goto(base);await page.waitForFunction(()=>!document.querySelector('#mode').options[1].disabled);assert.match(await page.locator('#readiness').innerText(),/knowledge 11 docs\/59 passages/);await sample();await page.locator('#mode').selectOption('ai');assert.match(await page.locator('#engine-note').innerText(),/Allow up to 5 minutes on CPU/);delay=500;await page.locator('#analyze').click();await page.locator('#report').filter({hasText:'Local technical references are ready'}).waitFor();assert.equal(await page.locator('#export').isDisabled(),true);assert.match(await page.locator('#report').innerText(),/Add a Call REST Action/);await page.locator('#export:not([disabled])').waitFor();delay=0;const visible=await page.locator('#report').innerText();assert.match(visible,/AI-observed visual evidence — unverified/i);assert.match(visible,/Technical references — retrieved guidance, not case evidence/);assert.match(visible,/Local AI · Qwen3-VL 4B · 0\.0s · Screenshot analyzed · 0 invalid citations removed/);assert.doesNotMatch(visible,/modelDigest/);assert.equal(await page.locator('.evidence-image').count(),1);assert.equal(await page.locator('.evidence-image').getAttribute('src'),await page.locator('#preview').getAttribute('src'));await page.screenshot({path:fileURLToPath(new URL('local-ai-mocked.png',outputDir)),fullPage:true});});
  await check('AI errors are displayed without demo fallback while retrieved references remain useful',async()=>{fail=true;await page.locator('#analyze').click();await page.locator('#error').filter({hasText:'AI response rejected'}).waitFor();assert.match(await page.locator('#report').innerText(),/Local technical references are ready/);assert.doesNotMatch(await page.locator('#report').innerText(),/AI synthesis/);assert.equal(await page.locator('#export').isDisabled(),true);fail=false;});
  await check('cancel prevents late results and permits a new request',async()=>{delay=1500;await page.locator('#analyze').click();await page.locator('#cancel').click();assert.match(await page.locator('#elapsed').innerText(),/Cancelled/);await page.waitForTimeout(1600);assert.equal(await page.locator('#report').innerText(),'');delay=0;await generate();});
  await check('unavailable model is actionable and disables AI',async()=>{ready=false;await page.locator('#refresh-status').click();await page.locator('#readiness').filter({hasText:'Model not installed'}).waitFor();assert.equal(await page.locator('#mode').inputValue(),'demo');assert.equal(await page.locator('#mode option[value=ai]').isDisabled(),true);});
  await check('reload clears case and app attempts no external network requests',async()=>{await page.reload();assert.equal(await page.locator('#description').inputValue(),'');assert.equal(await page.locator('#report').innerText(),'');assert.deepEqual(external,[]);assert.deepEqual(errors,[]);});
  await check('small-screen layout has no horizontal overflow',async()=>{await page.setViewportSize({width:390,height:844});await sample();await generate();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:fileURLToPath(new URL('mobile-demo.png',outputDir)),fullPage:true});});
  await writeFile(new URL('browser-results.json',outputDir),JSON.stringify({passed:checks,externalRequests:external,pageErrors:errors,ai:'Mocked Ollama integration; real-model evaluation is separate.'},null,2));
}finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}
