export function validateReport(r,input){
 if(!r||typeof r.summary!=='string')throw Error('Missing summary');
 for(const k of ['steps','questions'])if(!Array.isArray(r[k])||!r[k].every(x=>typeof x==='string'))throw Error('Invalid '+k);
 for(const [key,fields] of Object.entries({observations:['text','source','quote'],hypotheses:['title','reason','check'],tests:['name','steps','expected']})){
  if(!Array.isArray(r[key])||!r[key].every(x=>x&&fields.every(f=>typeof x[f]==='string')))throw Error('Invalid '+key);
 }
 const total=r.observations.length;
 r.observations=r.observations.filter(o=>['description','logs'].includes(o.source)&&o.quote.trim()&&input[o.source].includes(o.quote));
 return {...r,discardedCitations:total-r.observations.length};
}
export function demoReport(input){
 const known=input.logs.includes('PATCH /api/accounts/1042 409')&&input.description.includes('disappears after refresh');
 return {mode:'demo',notice:'Rule-based demo, not AI analysis. Screenshots are previewed but not analyzed in this mode.',summary:known?'Account update appears successful, but the changed value does not persist after refresh.':'Investigation checklist prepared from your report. Enable local AI for tailored analysis.',observations:[{text:'Reported behavior (not independently verified).',source:'description',quote:input.description},...(known?[{text:'The supplied log records a failed save request.',source:'logs',quote:'PATCH /api/accounts/1042 409'}]:[])],steps:known?['Open account 1042 in the reported environment.','Change the account name and select Save.','Record the notification and the PATCH response in the Network panel.','Refresh the page and compare the displayed name with the submitted value.']:['Open the affected screen in the reported environment.','Repeat the action described in the report, recording exact inputs.','Capture the actual result, expected result, and network or console evidence.','Repeat in a fresh session to check consistency.'],questions:[...(!input.environment?['Which environment, browser, and application version are affected?']:[]),'What is the expected behavior and how often does the issue occur?','Does this happen for another user or record?'],hypotheses:known?[{title:'Success notification may ignore a failed response',reason:'The report describes success while the log records HTTP 409. The UI error-handling path needs inspection.',check:'Trace the Save handler and confirm success is displayed only after a successful response.'},{title:'A record version conflict may prevent persistence',reason:'A 409 response can indicate a conflict; the response body is needed to identify its exact meaning.',check:'Inspect the response body and compare submitted and current record versions.'}]:[],tests:[{name:'Successful operation',steps:'Perform the reported action with valid inputs and a successful backend response.',expected:'The UI reflects the saved state after refresh.'},{name:'Failed request',steps:'Make the backend return an error for the operation in a test environment.',expected:'The UI displays an error and does not report success.'},{name:'Repeat after refresh',steps:'Repeat the workflow, refresh, and revisit the affected record.',expected:'Displayed state agrees with persisted backend state.'}],discardedCitations:0};
}
